class Player

  attr_accessor *%i[
    id
    realm
    player_name
    race
    gender
    grand_company
    level_gladiator
    level_pugilist
    level_marauder
    level_lancer
    level_archer
    level_rogue
    level_conjurer
    level_thaumaturge
    level_arcanist
    level_darkknight
    level_machinist
    level_astrologian
    level_carpenter
    level_blacksmith
    level_armorer
    level_goldsmith
    level_leatherworker
    level_weaver
    level_alchemist
    level_culinarian
    level_miner
    level_botanist
    level_fisher
    p30days
    p60days
    p90days
    p180days
    p270days
    p360days
    p450days
    p630days
    p960days
    prearr
    prehw
    artbook
    beforemeteor
    beforethefall
    soundtrack
    saweternalbond
    sightseeing
    arr_25_complete
    comm50
    moogleplush
    hildibrand
    ps4collectors
    dideternalbond
    arrcollector
    kobold
    sahagin
    amaljaa
    sylph
    hw_complete
    hw_31_complete
    hw_33_complete
    legacy_player
    ifrit_ex_mount
    garuda_ex_mount
    titan_ex_mount
    levi_ex_mount
    ramuh_ex_mount
    shiva_ex_mount
    all_6_ponies_mount
    diadem_99_mount
    bismarck_ex_mount
    thordan_ex_mount
    ravana_ex_mount
    sepi_ex_mount
    nidhogg_ex_mount
  ]

  def initialize
  end

end
